# Generated by Django 3.2.9 on 2021-11-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtheriumData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_time', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=20, max_digits=50)),
                ('high_price', models.DecimalField(decimal_places=20, max_digits=50)),
                ('low_price', models.DecimalField(decimal_places=20, max_digits=50)),
                ('close_price', models.DecimalField(decimal_places=20, max_digits=50)),
                ('volume', models.DecimalField(decimal_places=20, max_digits=50)),
                ('quote_volume', models.DecimalField(decimal_places=20, max_digits=50)),
            ],
            options={
                'ordering': ['close_time'],
            },
        ),
    ]
